name: sudoku
description: "Sudoku app written in flutter."

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  stop_watch_timer: ^3.0.2

  path_provider: ^2.1.1

  ffi: ^2.1.0

  provider: ^6.1.1

  flutter_colorpicker: ^1.0.3

  settings_ui: ^2.0.2

  flutter_localizations: 
    sdk: flutter
  localization: ^2.1.1

  rust_builder:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.22

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  golden_toolkit: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: 8.0.2
  integration_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/guides/
    - lib/i18n/
