// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.12.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String generateSudoku({dynamic hint}) =>
    RustLib.instance.api.generateSudoku(hint: hint);

String? uniqueSolution({required String sudokuString, dynamic hint}) =>
    RustLib.instance.api.uniqueSolution(sudokuString: sudokuString, hint: hint);

(int, bool) getRating({required String sudokuString, dynamic hint}) =>
    RustLib.instance.api.getRating(sudokuString: sudokuString, hint: hint);
